### ISSUE TITLE
控制啥的？

### ISSUE THREAD

**Issue by geekmc** [DigDream/RevealJS-remote-control#1]
写个使用文档可好

**Comment by dubuqingfeng** [comment]
控制网页版PPT的，即Revealjs那种效果。
今天拍了个测试视频，可以看一下。
http://v.youku.com/v_show/id_XMTY4NDgwMjA1Mg==.html
这个主要是想参加华为的docker马拉松的。文档会过几天写。

**Comment by geekmc** [comment]
good
